#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use PasswordGen\Commands\DeletePasswordCommand;
use PasswordGen\Commands\GeneratePasswordCommand;
use PasswordGen\Commands\UpdateSiteCommand;
use PasswordGen\Commands\ShowPasswordsCommand;
use PasswordGen\Commands\MigrateCommands;

$application = new Application();
$application->add(new DeletePasswordCommand());
$application->add(new GeneratePasswordCommand());
$application->add(new UpdateSiteCommand());
$application->add(new ShowPasswordsCommand());
$application->add(new MigrateCommands());
try {
    $application->run();
} catch (Exception $e) {
    error_log($e->getMessage());
}